from turtle import *
import time

start = Turtle()

s = Screen()
s.bgcolor("black")
start.speed(10)
start.penup()
start.setposition(-20, -350)
start.pendown()

start.begin_fill()
start.color("red")
start.circle(300)
start.end_fill()
start.penup()
start.setposition(-20, -260)
start.pendown()

start.begin_fill()
start.color("white")
start.circle(230)
start.end_fill()
start.penup()
start.setposition(0, -100)
start.pendown()

start.begin_fill()
start.color("red")
start.pensize(2)
start.pencolor("grey")
start.backward(100)
start.left(60)
start.backward(200)
start.right(60)
start.backward(85)
start.right(115)
start.backward(600)
start.right(65)
start.backward(130)
start.right(90)
start.backward(440)
start.right(90)
start.backward(100)
start.right(90)
start.backward(65)
start.end_fill()

start.penup()
start.setposition(0, -50)
start.pendown()
start.pensize(2)

start.begin_fill()
start.color("white")
start.pencolor("grey")
start.right(90)
start.forward(90)
start.right(120)
start.forward(170)
start.right(150)
start.forward(150)
start.end_fill()

time.sleep(5)

